
// Example usage of helpers: Name Registry
// Create the contract, register the key 123, set the value 456

var web3 = require('web3')
var ethlightjs = require('ethlightjs')
var txutils = ethlightjs.txutils
var helpers = ethlightjs.helpers
var web3api = require('ethlightjs/lib/blockchainapi/web3api')

web3.setProvider(new web3.providers.HttpProvider("http://localhost:8545"));

var source = '\ncontract NameCoin {\n\n    struct Item {\n\taddress owner;\n\tuint value;\n    }\n\n    mapping (uint => Item) registry;\n\n    function register(uint key) {\n\tif (registry[key].owner == 0) {\n\t    registry[key].owner = msg.sender;\n\t}\n    }\n\n    function transferOwnership(uint key, address newOwner) {\n\tif (registry[key].owner == msg.sender) {\n\t    registry[key].owner = newOwner;\n\t}\n    }\n\n    function setValue(uint key, uint newValue) {\n\tif (registry[key].owner == msg.sender) {\n\t    registry[key].value = newValue;\n\t}\n    }\n\n    function getValue(uint key) constant returns (uint value) {\n\treturn registry[key].value;\n    }\n\n    function getOwner(uint key) constant returns (address owner) {\n\treturn registry[key].owner;\n    }\n}\n'

//var privkey = '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824'
//keystore.addPrivateKey(privkey, 'mypassword')

var seed = 'unhappy nerve cancel reject october fix vital pulse cash behind curious bicycle'
var keystore = new ethlightjs.keystore(seed, 'mypassword')

var sendingAddr = keystore.getAddresses()[0]
console.log(sendingAddr)
var nonce = web3api.getNonce(sendingAddr)
console.log('Nonce: ' + nonce)
console.log('Balance: ' + web3api.getBalance(sendingAddr))
var compiled = web3.eth.compile.solidity(source)
var code = compiled.NameCoin.code.slice(2)

txOptions = {
    gasLimit: 3000000,
    nonce: nonce
}

// create, sign and inject transaction
var contractAddr = helpers.sendCreateContractTx(code, sendingAddr, txOptions, web3api, keystore, 'mypassword')
console.log('Contract address: ' + contractAddr)

// contract json abi, this is autogenerated using solc CLI
var abi = [{"constant":true,"inputs":[{"name":"key","type":"uint256"}],"name":"getValue","outputs":[{"name":"value","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"key","type":"uint256"},{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"key","type":"uint256"},{"name":"newValue","type":"uint256"}],"name":"setValue","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"key","type":"uint256"}],"name":"getOwner","outputs":[{"name":"owner","type":"address"}],"type":"function"},{"constant":false,"inputs":[{"name":"key","type":"uint256"}],"name":"register","outputs":[],"type":"function"}]

// TX to register the key 123
txOptions.nonce += 1
helpers.sendFunctionTx(abi, contractAddr, 'register', [123], sendingAddr, txOptions, web3api, keystore, 'mypassword')

// TX to set the value corresponding to key 123 to 456
txOptions.nonce += 1
helpers.sendFunctionTx(abi, contractAddr, 'setValue', [123, 456], sendingAddr, txOptions, web3api, keystore, 'mypassword')

// Check that the owner is sendingAddr
var blockNumber = web3.eth.blockNumber
var b = blockNumber
console.log('Waiting for blocks...')
while (b == blockNumber) {
    b = web3.eth.blockNumber
}
console.log('New blocks found. Waiting for some more blocks...')
blockNumber = b
while (b == blockNumber) {
    b = web3.eth.blockNumber
}

var contractAddr = contractAddr
var myContract = web3.eth.contract(abi).at('0x' + contractAddr)
var owner = myContract.getOwner(123)
console.log('Owner: ' + owner)

// Check the value of key 123
var val = myContract.getValue(123)
console.log('Value: ' + val)
